/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example

import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.server.testing.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

@DisplayName("endpoints")
class ApplicationTest {

    @Test
    @DisplayName("root path returns 'Hello, world!'")
    fun testRoot() = testApplication {
        val response = client.get("/")

        assertThat(HttpStatusCode.OK).isEqualTo(response.status)
        assertThat("Hello, world!").isEqualTo(response.bodyAsText())
    }
}
