services:
  ktor:
    container_name: ktor-service
    image: gradle:8.9.0-jdk17
    ports:
      - "8080:8080"
    volumes:
        - $PWD:/app
    working_dir: /app
    environment:
      KTOR_ENV: "local"
      APP_OPTS: "-Dio.ktor.development=true -XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
    command: [ "./gradlew", "run" ]
    restart: unless-stopped
